grpc:
  server:
    port: ${PORT:9000}
  client:
    GLOBAL:
      address: ${AUTH_ENDPOINT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_ADDR}:${DB_PORT:5432}/${DB_NAME}
  profiles:
    active: ${PROFILE:prod}
mybatis:
  mapper-locations: mapper/**/*.xml