grpc:
  server:
    port: ${PORT:9000}
  client:
    GLOBAL:
      address: ${AUTH_ENDPOINT}
      negotiation-type: plaintext
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_ADDR}:${DB_PORT:5432}/${DB_NAME}
  profiles:
    active: ${PROFILE:prod}
  redis:
    host: ${REDIS_ADDR}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWD}
mybatis:
  mapper-locations: mapper/**/*.xml
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 0.5