name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Build jar
        run: mvn package
        env:
          AUTH_ENDPOINT: localhost
          DB_USER: test
          DB_PASS: test
          DB_ADDR: localhost
          DB_NAME: test
      
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          path: ./target/forum.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: artifact
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag xmumy/forum:${GITHUB_RUN_NUMBER}

      - name: Publish
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u ctrysbita --password-stdin
          docker push xmumy/forum:${GITHUB_RUN_NUMBER}
